### ISSUE TITLE
Bypass Password Hashing

### ISSUE THREAD

**Issue by mitchelladams** [andrewlimaza/import-users-from-csv#12]
I'm importing Joomla users into WordPress and would like to store the Joomla hashed version of their password during import in the user_pass field. I'll be checking the password later on.

Is it possible to bypass WordPress re-hashing the user_pass data or am I better off just doing a database direct import?

**Comment by andrewlimaza** [comment]
@mitchelladams I recommend to tweak the plugins code to your needs as WordPress does this by default with the functions we use to create the WP user.

Maybe a way around this is to import the users and then run a SQL script to directly update the hash value. I don't think this is something that we would support right now as it's not easy to achieve from the PHP side of things.

**Comment by mitchelladams** [comment]
Thank you Andrew.
